version: '3'

services:

  bot-201:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: bot
    #env_file:
    #  - /envs/201.env
    command: python bot/bot.py

  bot-202:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: bot
    #env_file:
    #  - /envs/202.env
    command: python bot/bot.py


  bot-341:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: bot
    #env_file:
    #  - ./341.env
    command: python bot/bot.py

  bot-staging:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: bot
    environment:
      - BOT_TOKEN
      - MONGODB_URI
      - QUEUE_URL
    command: python bot/bot.py

  bot-test:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: bot
    command: python bot/test.py
    environment:
      - BOT_TOKEN
      - MONGODB_URI
      - QUEUE_URL
      - TEST_BOT_TOKEN
    depends_on:
      - bot-staging