name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag bot

    - name: Run tests
      run: |
        docker-compose up bot-test
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        QUEUE_URL: ${{ secrets.QUEUE_URL }}
        TEST_BOT_TOKEN: $ {{ secrets.TEST_BOT_TOKEN }}


